### ISSUE TITLE
PHP 7.1 type declarations

### ISSUE THREAD

**Issue by paveljanda** [contributte/middlewares#2]
@f3l1x Would you appreciate a PR with PHP 7.1 type declarations and strict_types declared in each file?

**Comment by f3l1x** [comment]
Yes, I would, but we have to wait until 2018, because this whole concept is used in one of my company and they'll use PHP 5.6 until end of 2017. It's only a few months. :-)

**Comment by paveljanda** [comment]
Creating new branch (`php71` or `v2` :P) would fix that..

**Comment by f3l1x** [comment]
Sure, but I don't want to waste time to maintenance 2 branches. :-)

**Comment by paveljanda** [comment]
I understand. Ping me in that issue when you're ready. :)
