### ISSUE TITLE
Playground or "how to start" docs part missing

### ISSUE THREAD

**Issue by lunak86** [contributte/middlewares#28]
I'm missing some real-life example or playground, something like to "how to start" or just link to some website.

For me, personally, the main problem is the first step. I will install the package, setup the index or bootstrap, but what next? 

Does that mean that when I configure the List in the config.neon file then these middlewares will be automatically applied to all website requests? What can I do when I wnat some middleware to be applied just on some of them (eg. authentication middleware only for admin module).

**Comment by mabar** [comment]
Sorry, I totally missed that.

You are right, just register extension, setup index.php and register middlewares you want.

- Middlewares are used for all requests.
- Each middleware could call next middleware or return response. So e.g. AuthenticationMiddleware returns response in case of unsuccessful authentication and left middlewares are not used.
- Each middleware calls next in a row so you could create branches through middleware which would decide which middleware would be called next.
- Conditional authentication in middleware could be based on target (controller, presenter) so you probably want use router and match that target with it.

**Comment by f3l1x** [comment]
@lunak86 Take a look at https://github.com/apitte/playground
