### ISSUE TITLE
AbstractApplication - on<Event>events - why not using Nette\SmartObject?

### ISSUE THREAD

**Issue by paveljanda** [contributte/middlewares#3]
When using Nette\SmartObject you no longer need to have that `::dispatch()` method that only fires all anonymous functions in an array. The method name is maybe also a little bit misleading. Is usually stand for "transfer something to something else", for example and request..

Also, shouldn't it be called for example `::addOnError()` instead of `onError()`?

**Comment by f3l1x** [comment]
Good point. `nette/http` has a dependency on `nette/utils` so it  wouldn't be a problem use `Nette\SmartObject`. Thanks.

**Comment by f3l1x** [comment]
Closed via https://github.com/contributte/middlewares/commit/b85650cb6a64c909189d25ff8539e2a7024d3a7b
