### ISSUE TITLE
TryCatchMiddleware::log() should not be private

### ISSUE THREAD

**Issue by northys** [contributte/middlewares#47]
I think that `TryCatchMiddleware::log()` should not be private so I can extend it easily without copying the whole class.

What I'm trying to achieve is to log exception object under `exception` key in `context` because sentry's monolog handler expect the exception to be there so it can be fully logged to sentry including stacktrace and so.

**Comment by northys** [comment]
Also I think that adding Throwable to `exception` key under monolog's context could be default but it's not necessary I can extend it by myself when the `log` method becomes `protected`.

**Comment by f3l1x** [comment]
Resolved.
