### ISSUE TITLE
Security - BasicAuthMiddleware

### ISSUE THREAD

**Issue by f3l1x** [contributte/middlewares#6]

**Comment by kralmichal** [comment]
Can we implement it basically like in this awesome library? 
https://github.com/oscarotero/psr7-middlewares/blob/master/src/Middleware/BasicAuthentication.php

**Comment by f3l1x** [comment]
@kralmichal Sure.

A few hints:

- inspire at (https://github.com/oscarotero/psr7-middlewares/blob/master/src/Middleware/BasicAuthentication.php)
- implement it in two modes 
  - a) Compare pure strings (foo === foo)
  - b) Compare pure string with hashes password (hash(foo) === hashed_foo)), for example with ARGON2 or sth like that
